/*
 * This source file was generated by the Gradle 'init' task
 */
package xyz.ps;

import java.io.*;
import javax.swing.*;
import java.awt.*;

public class App {

    public static void gui() {
        

        JFrame frame = new JFrame(); // Creating instance of JFrame
        
            // Buttons

            /*
            JButton button1 = new JButton("button#1"); // Creating instance of JButton
            button1.setBounds(100, 200, 100, 100); // x axis, y axis, width, height
            frame.add(button1); // adding button in JFrame

            JButton button2 = new JButton("button#2"); // Creating instance of JButton
            button2.setBounds(200, 200, 100, 100); // x axis, y axis, width, height
            frame.add(button2); // adding button in JFrame
            */

            // Labels

            Label l1 = new Label("Process Priority");
            l1.setBounds(100, 50, 120, 80);
            frame.add(l1);

            // CheckBox created
            Checkbox c2 = new Checkbox("Real-Time");
            c2.setBounds(100, 150, 200, 50);
            frame.add(c2);

            // CheckBox created
            Checkbox c3 = new Checkbox("High");
            c3.setBounds(100, 200, 200, 50);
            frame.add(c3);

            // CheckBox created
            Checkbox c4 = new Checkbox("Medium");
            c4.setBounds(100, 250, 200, 50);
            frame.add(c4);



        // Config frame

        frame.setSize(500, 600); // 400 width and 500 height
        frame.setLayout(null); // using no layout managers
        frame.setVisible(true); // making the frame visible
        frame.setLocationRelativeTo(null); // Centers the frame on the screen
        frame.setResizable(false); // Disable window resizing

    }

    public static void main(String[] args) {
    
        gui();

    }
}